#!/usr/bin/sh

# zettel: creates a new zettel on Zettelkasten repository

ZETTAG=`utctag`
REPOSDIR="${HOME}/repos/github.com/${USER}"
ZETTELKASTENDIR="${REPOSDIR}/zettelkasten/"

main() {
    cd "${ZETTELKASTENDIR}"
    mkdir "${ZETTAG}"
    touch "${ZETTAG}/README.md"
    echo "Zettel:  ${ZETTAG}" > "${ZETTAG}/README.md"
    vi "${ZETTAG}/README.md"
}

main
